title: AlgoRandos
author: AlgoRandos
email: hello@algorandos.art

# social links
twitter_username: algorandos
github_username:  algorandos

# Build settings
theme: minima


plugins:
 - jekyll-seo-tag
